apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: tron
  name: tron
spec:
  ports:
  - nodeport: 30001
    port: 8000
    protocol: TCP
    targetPort: 8000
  type: LoadBalancer
  selector:
    io.kompose.service: tron
status:
  loadBalancer: {}
